### ISSUE TITLE
bug: config differences in cli subcommands | "Failed to read genesis file..."

### ISSUE THREAD

**Issue by justinfrevert** [keep-starknet-strange/madara#1196]
# Bug Report

**Madara version:**

branch: `main `
version: `0.4.0`

**Current behavior:**

With default arguments, the `run` and `setup` subcommands _read_ and _write_ from separate locations, respectively. This is caused by different default behavior if the chain id is omitted. This results in confusing errors on mismatched paths if a developer follows the documentation steps. 

As a side note: the expected behavior occurs if the user passes in `--chain dev` for the `setup` subcommand, but this isn't mentioned in the `--help` for `setup` but it should be.

**Expected behavior:**

Both commands should accept reasonable defaults, and I think the reasonable default is `dev` for local development. Documentation including readmes and CLI help cmds should reflect this as well as any overrides. Tests should confirm the behavior.

**Steps to reproduce:**

Attempt the setup function. It should place the files in a location which the filesystem lookups in the `run` subcommand won't expect:
`cargo run --release -- setup --from-remote` 
Run it:
`cargo run --release -- --dev `
``

This should panic with:
```
====================

Version: 0.4.0-5003054b326

   0: backtrace::capture::Backtrace::new
   1: sp_panic_handler::set::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/std/src/panicking.rs:733:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/std/src/panicking.rs:621:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/std/src/sys_common/backtrace.rs:170:18
   5: rust_begin_unwind
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/std/src/panicking.rs:617:5
   6: core::panicking::panic_fmt
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/core/src/panicking.rs:67:14
   7: core::result::unwrap_failed
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/core/src/result.rs:1652:5
   8: madara::chain_spec::load_genesis
   9: madara::chain_spec::development_config::{{closure}}
  10: sc_chain_spec::chain_spec::GenesisSource<G>::resolve
  11: <sc_chain_spec::chain_spec::ChainSpec<G,E> as sp_runtime::BuildStorage>::assimilate_storage
  12: sp_runtime::BuildStorage::build_storage
  13: madara::genesis_block::MadaraGenesisBlockBuilder<Block,B,E>::new
  14: madara::service::new_full
  15: tokio::runtime::park::CachedParkThread::block_on
  16: tokio::runtime::runtime::Runtime::block_on
  17: sc_cli::runner::Runner<C>::run_node_until_exit
  18: madara::command::run
  19: std::sys_common::backtrace::__rust_begin_short_backtrace
  20: std::rt::lang_start::{{closure}}
  21: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/std/src/panicking.rs:524:40
      std::panicking::try
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/std/src/panicking.rs:488:19
      std::panic::catch_unwind
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/std/src/panicking.rs:524:40
      std::panicking::try
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/std/src/panicking.rs:488:19
      std::panic::catch_unwind
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/249595b7523fc07a99c1adee90b1947739ca0e5b/library/std/src/rt.rs:148:20
  22: _main


Thread 'main' panicked at 'Failed to read genesis file. Please run `madara setup` before opening an issue.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/node/src/chain_spec.rs:157
```

Reproduced on macbook T2 macos Ventura Version 13.0 (22A8380)

**Related code:**

[Default behavior for running the node](https://github.com/keep-starknet-strange/madara/blob/2afd5fdfa1085332bf566a10f5f19617fe40fb8b/crates/node/src/commands/run.rs#L77), which defaults a chain id `dev` for the path
vs.
The setup code's [fallback](https://github.com/keep-starknet-strange/madara/blob/2afd5fdfa1085332bf566a10f5f19617fe40fb8b/crates/node/src/commands/setup.rs#L54) to an empty string. 

**Other information:**

**Comment by justinfrevert** [comment]
Ah, yeap I was looking at an old doc page which caused the confusion. Thanks for checking
